name: Test Auto Publisher

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # تم التحديث لتجنب تحذير جوجل

      - name: Install Dependencies
        run: |
          pip install feedparser
          pip install beautifulsoup4 # مكتبة سحب عناوين H2 و H3
          pip install google-genai # مكتبة جيميناي الجديدة والمحدثة

      - name: Run Main Script
        env:
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }} # سحبنا قائمة المفاتيح
        run: python main.py

      - name: Save Memory
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add published.txt
          git commit -m "تحديث ذاكرة المقالات" || echo "لا يوجد تحديث"
          git push
